import Image from "next/image";

const IconSlider = () => {
  return (
    <div className="p-10 flex flex-wrap justify-center gap-4">
      <Image
        src="https://cdn-icons-png.flaticon.com/128/5968/5968267.png"
        width={50}
        height={50}
        alt="html"
        className="flex-shrink-0"
      />
      <Image
        src="https://cdn-icons-png.flaticon.com/128/5968/5968242.png"
        width={50}
        height={50}
        alt="css"
        className="flex-shrink-0"
      />
      <Image
        src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDML5CFq70Y9FJ52YnyCjfdyUA3g9B6is_jA&s"
        width={50}
        height={50}
        alt="tailwind"
        className="flex-shrink-0"
      />
      <Image
        src="https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/styled-components/styled-components.png"
        width={50}
        height={50}
        alt="styled-components"
        className="flex-shrink-0"
      />
      <Image
        src="https://cdn-icons-png.flaticon.com/128/5968/5968292.png"
        width={50}
        height={50}
        alt="js"
        className="flex-shrink-0"
      />
      <Image
        src="https://cdn-icons-png.flaticon.com/128/5968/5968381.png"
        width={50}
        height={50}
        alt="ts"
        className="flex-shrink-0"
      />
      <Image
        src="https://cdn-icons-png.flaticon.com/128/875/875209.png"
        width={50}
        height={50}
        alt="react"
        className="flex-shrink-0"
      />
      <Image
        src="https://cdn-icons-png.flaticon.com/128/919/919825.png"
        width={50}
        height={50}
        alt="nodejs"
        className="flex-shrink-0"
      />
      <Image
        src="https://w7.pngwing.com/pngs/925/447/png-transparent-express-js-node-js-javascript-mongodb-node-js-text-trademark-logo.png"
        width={50}
        height={50}
        alt="expressjs"
        className="flex-shrink-0"
      />
      <Image
        src="https://cdn.worldvectorlogo.com/logos/mongodb-icon-2.svg"
        width={50}
        height={50}
        alt="mongodb"
        className="flex-shrink-0"
      />
      <Image
        src="https://www.datocms-assets.com/98835/1684410508-image-7.png"
        width={50}
        height={50}
        alt="nextjs"
        className="flex-shrink-0"
      />
      <Image
        src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSf6vvGX2uMfpt06Tb5pLRRWgC6W4V7Sgz2A&s"
        width={50}
        height={50}
        alt="sapui5"
        className="flex-shrink-0"
      />
      <Image
        src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/SAP_2011_logo.svg/2560px-SAP_2011_logo.svg.png"
        width={50}
        height={50}
        alt="sap"
        className="flex-shrink-0"
      />
      <Image
        src="https://devblogs.microsoft.com/odata/wp-content/uploads/sites/23/2019/02/ODataLogo-250.png"
        width={50}
        height={50}
        alt="odata"
        className="flex-shrink-0"
      />
      <Image
        src="https://cdn-icons-png.flaticon.com/128/136/136526.png"
        width={50}
        height={50}
        alt="xml"
        className="flex-shrink-0"
      />
    </div>
  );
};

export default IconSlider;
